/**
 * Copyright (C) 2013 Gaia Transparence
 * Gaia Transparence, 1 allée Paul Barillon - 94300 VINCENNES
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3.0 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.gaia.gui.referentials;

/**
 *
 * @author Jawhar Kamoun
 */
import java.util.List;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import org.gaia.dao.jade.DAOCallerAgent;
import org.gaia.dao.legalEntity.LegalEntityAccessor;
import org.gaia.domain.legalEntity.CreditContractType;
import org.gaia.domain.utils.StringUtils;
import org.gaia.gui.common.GaiaTopComponent;
import org.gaia.gui.common.MenuManager;
import org.gaia.gui.utils.GUIUtils;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays ratings.
 */
@ConvertAsProperties(dtd = "-//org.gaia.gui.referentials//CreditContract//EN", autostore = false)
@TopComponent.Description(preferredID = "CreditContractTopComponent", persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.gaia.gui.referentials.CreditContractTopComponent")
@ActionReference(path = "Menu" + MenuManager.CreditContractTopComponentMenu, position = MenuManager.CreditContractTopComponent)
@TopComponent.OpenActionRegistration(displayName = "#CTL_CreditContractAction", preferredID = "CreditContractTopComponent")
@Messages({"CTL_CreditContractAction=Credit Contract", "CTL_CreditContractTopComponent=Credit Contract", "HINT_CreditContractTopComponent=This is a Credit Contract window"})
public final class CreditContractTopComponent extends GaiaTopComponent {

    private static final Logger logger = Logger.getLogger(CreditContractTopComponent.class);

    public CreditContractTopComponent() {
        initComponents();
        setName(Bundle.CTL_CreditContractTopComponent());
        setToolTipText(Bundle.HINT_CreditContractTopComponent());
    }

    @Override
    public void initContext() {
        List<String> creditEvents = (List) DAOCallerAgent.callMethod(LegalEntityAccessor.class, LegalEntityAccessor.GET_CREDIT_EVENTS);
        GUIUtils.fillCombo(jComboEventList, creditEvents);

        List<String> creditContracts = (List) DAOCallerAgent.callMethod(LegalEntityAccessor.class, LegalEntityAccessor.GET_CREDIT_CONTRACT_TYPE_NAMES);
        GUIUtils.fillComboWithNullFirst(contractNameComboBox, creditContracts);
    }

    public void setActiveContract(String name) {
        contractNameComboBox.setSelectedItem(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        creditEventBackStopLabel = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        corporateLabel = new javax.swing.JLabel();
        contractNameComboBox = new javax.swing.JComboBox();
        creditEventLabel = new javax.swing.JLabel();
        creditEventsTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        corporateDayLabel = new javax.swing.JLabel();
        jComboEventList = new javax.swing.JComboBox();
        jButtonAddEvent = new javax.swing.JButton();
        jButtonRemoveEvent = new javax.swing.JButton();
        corporateEventsBackStopDate = new javax.swing.JFormattedTextField();
        creditEventsBackStopDateTextField = new javax.swing.JFormattedTextField();

        jPanel2.setBackground(new java.awt.Color(245, 252, 253));

        jPanel1.setBackground(new java.awt.Color(254, 252, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        org.openide.awt.Mnemonics.setLocalizedText(creditEventBackStopLabel, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.creditEventBackStopLabel.text")); // NOI18N

        jButtonDelete.setBackground(new java.awt.Color(195, 229, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jButtonDelete, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.jButtonDelete.text")); // NOI18N
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSave.setBackground(new java.awt.Color(195, 229, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jButtonSave, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.jButtonSave.text")); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonNew.setBackground(new java.awt.Color(195, 229, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jButtonNew, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.jButtonNew.text")); // NOI18N
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.nameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(corporateLabel, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.corporateLabel.text")); // NOI18N

        contractNameComboBox.setBackground(new java.awt.Color(255, 255, 255));
        contractNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        contractNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractNameComboBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(creditEventLabel, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.creditEventLabel.text")); // NOI18N

        creditEventsTextField.setEditable(false);
        creditEventsTextField.setText(org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.creditEventsTextField.text")); // NOI18N
        creditEventsTextField.setName("creditEventsTextField"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.jLabel6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(corporateDayLabel, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.corporateDayLabel.text")); // NOI18N

        jComboEventList.setBackground(new java.awt.Color(255, 255, 255));
        jComboEventList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));

        jButtonAddEvent.setBackground(new java.awt.Color(195, 229, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jButtonAddEvent, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.jButtonAddEvent.text")); // NOI18N
        jButtonAddEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddEventActionPerformed(evt);
            }
        });

        jButtonRemoveEvent.setBackground(new java.awt.Color(195, 229, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jButtonRemoveEvent, org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.jButtonRemoveEvent.text")); // NOI18N
        jButtonRemoveEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveEventActionPerformed(evt);
            }
        });

        corporateEventsBackStopDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        corporateEventsBackStopDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        corporateEventsBackStopDate.setText(org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.corporateEventsBackStopDate.text")); // NOI18N

        creditEventsBackStopDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        creditEventsBackStopDateTextField.setText(org.openide.util.NbBundle.getMessage(CreditContractTopComponent.class, "CreditContractTopComponent.creditEventsBackStopDateTextField.text_1")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(creditEventsTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(creditEventBackStopLabel)
                                    .addComponent(creditEventLabel)
                                    .addComponent(nameLabel))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(contractNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jComboEventList, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonAddEvent)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonRemoveEvent))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(creditEventsBackStopDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addGap(38, 38, 38)
                                        .addComponent(corporateLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(corporateEventsBackStopDate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(corporateDayLabel))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDelete)))
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditEventBackStopLabel)
                    .addComponent(corporateLabel)
                    .addComponent(corporateDayLabel)
                    .addComponent(corporateEventsBackStopDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditEventsBackStopDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboEventList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddEvent)
                    .addComponent(jButtonRemoveEvent)
                    .addComponent(creditEventLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditEventsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonNew))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * delete
     * @param evt
     */
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try {
            if (contractNameComboBox.getSelectedItem() == null) {
                return;
            }
            String name = contractNameComboBox.getSelectedItem().toString();
            DAOCallerAgent.callMethod(LegalEntityAccessor.class, LegalEntityAccessor.DELETE_CREDIT_CONTRACT_TYPE_BY_NAME, name);
        } catch (Exception ex) {
            logger.error(StringUtils.formatErrorMessage(ex));
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * store data
     * @param evt
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            if (StringUtils.isEmptyString(creditEventsTextField.getText())) {
                JOptionPane.showMessageDialog(this, "Please Fill Credit Events ");
                return;
            }
            Object item = contractNameComboBox.getSelectedItem();
            if (item == null) {
                item = JOptionPane.showInputDialog("Please enter the contract name");
            }
            if (item == null) {
                return;
            }
            String name = item.toString();

            if (!StringUtils.isEmptyString(name)) {
                CreditContractType contractType = (CreditContractType) DAOCallerAgent.callMethod(LegalEntityAccessor.class, LegalEntityAccessor.GET_CREDIT_CONTRACT_TYPE_BY_NAME, name);
                if (contractType == null) {
                    contractType = new CreditContractType();
                    contractType.setCreditContractTypeName(name);
                }
                contractType.setCreditBackStopDate(Short.parseShort(creditEventsBackStopDateTextField.getText()));
                contractType.setCorporateBackStopDate(Short.parseShort(corporateEventsBackStopDate.getText()));
                contractType.setEventList(creditEventsTextField.getText());
                DAOCallerAgent.callMethod(LegalEntityAccessor.class, LegalEntityAccessor.STORE_CREDIT_CONTRACT_TYPE, contractType);
            }
        } catch (Exception ex) {
            logger.error(StringUtils.formatErrorMessage(ex));

        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed

        clearFields(this);
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonAddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddEventActionPerformed

        if (jComboEventList.getSelectedItem() != null) {
            if (creditEventsTextField.getText().length() > 0) {
                creditEventsTextField.setText(creditEventsTextField.getText() + StringUtils.COMMA + jComboEventList.getSelectedItem().toString());
            } else {
                creditEventsTextField.setText(jComboEventList.getSelectedItem().toString());
            }
        }
    }//GEN-LAST:event_jButtonAddEventActionPerformed

    private void jButtonRemoveEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveEventActionPerformed

        int i = creditEventsTextField.getText().lastIndexOf(StringUtils.COMMA);
        if (creditEventsTextField.getText().length() > 0) {
            if (i > 0) {
                creditEventsTextField.setText(creditEventsTextField.getText().substring(0, i));
            } else {
                creditEventsTextField.setText(StringUtils.EMPTY_STRING);
            }
        }
    }//GEN-LAST:event_jButtonRemoveEventActionPerformed

    private void contractNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractNameComboBoxActionPerformed
        load();
    }//GEN-LAST:event_contractNameComboBoxActionPerformed

    /**
     * load the contract
     */
    private void load() {
        if (contractNameComboBox.getSelectedItem() != null) {
            String name = contractNameComboBox.getSelectedItem().toString();
            CreditContractType contractType = (CreditContractType) DAOCallerAgent.callMethod(LegalEntityAccessor.class, LegalEntityAccessor.GET_CREDIT_CONTRACT_TYPE_BY_NAME, name);
            if (contractType != null) {
                if (contractType.getCreditBackStopDate() != null) {
                    creditEventsBackStopDateTextField.setText(contractType.getCreditBackStopDate().toString());
                } else {
                    creditEventsBackStopDateTextField.setText(StringUtils.EMPTY_STRING);
                }
                if (contractType.getCorporateBackStopDate() != null) {
                    corporateEventsBackStopDate.setText(contractType.getCorporateBackStopDate().toString());
                } else {
                    corporateEventsBackStopDate.setText(StringUtils.EMPTY_STRING);
                }
                if (contractType.getEventList() != null) {
                    creditEventsTextField.setText(contractType.getEventList());
                } else {
                    creditEventsTextField.setText(StringUtils.EMPTY_STRING);
                }
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox contractNameComboBox;
    private javax.swing.JLabel corporateDayLabel;
    private javax.swing.JFormattedTextField corporateEventsBackStopDate;
    private javax.swing.JLabel corporateLabel;
    private javax.swing.JLabel creditEventBackStopLabel;
    private javax.swing.JLabel creditEventLabel;
    private javax.swing.JFormattedTextField creditEventsBackStopDateTextField;
    private javax.swing.JTextField creditEventsTextField;
    private javax.swing.JButton jButtonAddEvent;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonRemoveEvent;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboEventList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        initContext();
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {

        p.setProperty("version", "1.0");

    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");

    }
}
