/**
 * Copyright (C) 2013 Gaia Transparence Gaia Transparence, 1 allée Paul Barillon
 * - 94300 VINCENNES
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3.0 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.gaia.gui.utils;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.apache.log4j.Logger;

/**
 *
 * @author Jawhar
 */
public class FieldValuesListChooser extends JPanel {

    private static final Logger logger = Logger.getLogger(FieldValuesListChooser.class);
    private DefaultTableModel valueListModel;
    private List<String> selectedValuesList;

    /**
     * Creates new form FieldValuesListChooser
     */
    public FieldValuesListChooser(List<String> listOfValues, List<String> _selectedValuesList) {
        initComponents();
        selectedValuesList = _selectedValuesList;
        if (selectedValuesList == null) {
            selectedValuesList = new ArrayList<>();
        }
        valueListTable.setAutoCreateRowSorter(false);
        valueListModel = (DefaultTableModel) valueListTable.getModel();
        TableColumn tableColumn = valueListTable.getColumnModel().getColumn(0);
        tableColumn.setCellEditor(valueListTable.getDefaultEditor(Boolean.class));
        tableColumn.setCellRenderer(valueListTable.getDefaultRenderer(Boolean.class));
        tableColumn.setHeaderRenderer(new CheckBoxHeader(new CheckBoxListener()));
        tableColumn.sizeWidthToFit();
        GUIUtils.packAllColumns(valueListTable);
        fillTable(listOfValues);
    }

    private void fillTable(List<String> listOfValues) {
        Vector<Vector<Object>> dataVector = new Vector<>();

        for (Object object : listOfValues) {
            Vector<Object> row = new Vector<>();
            row.add(selectedValuesList.contains(object));
            row.add(object.toString());
            dataVector.add(row);
        }
        valueListModel.getDataVector().removeAllElements();
        valueListModel.getDataVector().addAll(dataVector);
        valueListTable.setModel(valueListModel);
        valueListModel.fireTableDataChanged();
    }

    public List<String> getSelectedValues() {
        selectedValuesList.clear();
        for (int x = 0; x < valueListTable.getRowCount(); x++) {
            Boolean selected = (Boolean) valueListTable.getValueAt(x, 0);
            if (selected) {
                selectedValuesList.add(valueListTable.getValueAt(x, 1).toString());
            }
        }
        return selectedValuesList;
    }

    class CheckBoxListener implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent e) {
            Object source = e.getSource();
            if (source instanceof AbstractButton == false) {
                return;
            }
            boolean checked = e.getStateChange() == ItemEvent.SELECTED;
            for (int x = 0; x < valueListTable.getRowCount(); x++) {
                valueListTable.setValueAt(checked, x, 0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPane = new javax.swing.JScrollPane();
        valueListTable = new javax.swing.JTable();

        valueListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPane.setViewportView(valueListTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable valueListTable;
    // End of variables declaration//GEN-END:variables
}
