/**
 * Copyright (C) 2013 Gaia Transparence
 * Gaia Transparence, 1 allée Paul Barillon - 94300 VINCENNES
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3.0 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.gaia.gui.common;

import java.util.Date;
import org.apache.log4j.Logger;
import org.gaia.domain.utils.StringUtils;

/**
 *
 * @author Benjamin Frerejean
 *
 */
public class DateEditorPanel extends GaiaPanel {

    private static final Logger logger = Logger.getLogger(DateEditorPanel.class);
    /**
     * Creates new form ProductReferences
     * @param value
     */
    public DateEditorPanel(Object value) {
        initComponents();
        for (int i=900;i>=0;i--){
            dayPlusComboBox.addItem(i);
        }
        dayPlusComboBox.addItem(null);
        for (int i=-1;i>=-900;i--){
            dayPlusComboBox.addItem(i);
        }
        dayPlusComboBox.setSelectedIndex(901);
        if (value!=null){
            if (value instanceof Integer){
                dayPlusComboBox.setSelectedItem(value);
            } else if (value instanceof String && value!=null){
                try {
                    Date date=dateFormatter.parse(value.toString());
                    jDateChooserDate.setDate(date);
                } catch (Exception e){
                    logger.error(StringUtils.formatErrorMessage(e));
                }
            }
        }
    }

    public Object getValue(){
        if (dayPlusComboBox.getSelectedItem()!=null){
            return dayPlusComboBox.getSelectedItem();
        }
        if (jDateChooserDate.getDate()!=null){
            return jDateChooserDate.getDate();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDateChooserDate = new com.toedter.calendar.JDateChooser(null,null,dateFormat,null);
        jLabel3 = new javax.swing.JLabel();
        dayPlusComboBox = new javax.swing.JComboBox();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jDateChooserDate.setBackground(new java.awt.Color(254, 252, 254));
        jDateChooserDate.setBorder(null);
        jDateChooserDate.setPreferredSize(new java.awt.Dimension(116, 20));
        jDateChooserDate.setRequestFocusEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(DateEditorPanel.class, "DateEditorPanel.jLabel3.text")); // NOI18N

        dayPlusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jDateChooserDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayPlusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dayPlusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooserDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox dayPlusComboBox;
    private com.toedter.calendar.JDateChooser jDateChooserDate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
