/**
 * Copyright (C) 2013 Gaia Transparence
 * Gaia Transparence, 1 allée Paul Barillon - 94300 VINCENNES
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3.0 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.gaia.gui.common;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import org.gaia.dao.jade.DAOCallerAgent;
import org.gaia.dao.trades.ProductReferenceTypeAccessor;
import org.gaia.domain.utils.StringUtils;
import org.gaia.domain.trades.ProductReference;
import org.gaia.domain.trades.ProductReferenceType;
import org.gaia.gui.utils.GUIUtils;

/**
 *
 * @author Benjamin Frerejean
 */
public class ProductReferencesPanel extends GaiaPanel {
    private static final Logger logger = Logger.getLogger(ProductReferencesPanel.class);

    /**
     * Creates new form ProductReferences
     */
     public ProductReferencesPanel(){
         this(null);
     }

    public ProductReferencesPanel(Collection<ProductReference> prodrefs) {
        try {
            initComponents();

            if (prodrefs==null){
                prodrefs = new ArrayList();
            }

            Vector<String> tableHeaders = GUIUtils.getHeader(jTableProductReferences);
            Vector tableData = new Vector();
            for (ProductReference pr : prodrefs){
                Vector<Object> oneRow = new Vector<Object>();
                oneRow.add(pr.getReferenceType());
                oneRow.add(pr.getValue());
                tableData.add(oneRow);
            }

            List<ProductReferenceType> referenceTypes=(List)DAOCallerAgent.callMethod(ProductReferenceTypeAccessor.class, ProductReferenceTypeAccessor.GET_ALL_PRODUCT_REFERENCE_TYPES);
            for (ProductReferenceType prt : referenceTypes){
                boolean found=false;
                for (ProductReference pr : prodrefs){
                    if (pr.getReferenceType().equals(prt.getReferenceType())) {
                        found =true;
                    }
                }
                if (!found){
                    Vector<Object> oneRow = new Vector<Object>();
                    oneRow.add(prt.getReferenceType());
                    oneRow.add("");
                    tableData.add(oneRow);
                }
            }
            jTableProductReferences.setModel(new MyTableModel(tableData, tableHeaders));
        } catch (Exception ex) {
                logger.error(StringUtils.formatErrorMessage(ex));
        }
    }

    public class MyTableModel extends DefaultTableModel{

        public MyTableModel (Vector tableData,Vector tableHeaders){
            super(tableData, tableHeaders);
        }
        @Override
         public boolean isCellEditable(int rowIndex, int columnIndex){

            /** Or whatever column index you want to be editable */
            return columnIndex == 1;
        }
    }
    public JTable getTable() {
        return jTableProductReferences;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductReferences = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTableProductReferences.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Reference", "Value"
            }
        ));
        jScrollPane1.setViewportView(jTableProductReferences);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductReferences;
    // End of variables declaration//GEN-END:variables
}
