/**
 * Copyright (C) 2013 Gaia Transparence Gaia Transparence, 1 allée Paul Barillon
 * - 94300 VINCENNES
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3.0 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.09.02 at 07:44:16 PM CEST
//
package org.gaia.markit.generated;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for indexType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="indexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}family"/>
 *         &lt;element ref="{}indexname"/>
 *         &lt;element ref="{}annex"/>
 *         &lt;element ref="{}series"/>
 *         &lt;element ref="{}version"/>
 *         &lt;element ref="{}ccy"/>
 *         &lt;element ref="{}indexfactor" minOccurs="0"/>
 *         &lt;element ref="{}red"/>
 *         &lt;element name="terms" type="{}termsType" maxOccurs="unbounded"/>
 *         &lt;element name="component" type="{}componentType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "indexType", propOrder = {
    "family",
    "indexname",
    "annex",
    "series",
    "version",
    "ccy",
    "indexfactor",
    "red",
    "terms",
    "component"
})
public class IndexType {

    @XmlElement(required = true)
    protected String family;
    @XmlElement(required = true)
    protected String indexname;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar annex;
    protected int series;
    @XmlElement(required = true)
    protected int version;
    @XmlElement(required = true)
    protected String ccy;
    protected BigDecimal indexfactor;
    @XmlElement(required = true)
    protected String red;
    @XmlElement(required = true)
    protected TermsType terms;

    public void setTerms(TermsType terms) {
        this.terms = terms;
    }
    @XmlElement(required = true)
    protected List<ComponentType> component;

    /**
     * Gets the value of the family property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFamily() {
        return family;
    }

    /**
     * Sets the value of the family property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFamily(String value) {
        this.family = value;
    }

    /**
     * Gets the value of the indexname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getIndexname() {
        return indexname;
    }

    /**
     * Sets the value of the indexname property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setIndexname(String value) {
        this.indexname = value;
    }

    /**
     * Gets the value of the annex property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getAnnex() {
        return annex;
    }

    /**
     * Sets the value of the annex property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setAnnex(XMLGregorianCalendar value) {
        this.annex = value;
    }

    /**
     * Gets the value of the series property.
     *
     */
    public int getSeries() {
        return series;
    }

    /**
     * Sets the value of the series property.
     *
     */
    public void setSeries(int value) {
        this.series = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link int }
     *
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link int }
     *
     */
    public void setVersion(int value) {
        this.version = value;
    }

    /**
     * Gets the value of the ccy property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCcy() {
        return ccy;
    }

    /**
     * Sets the value of the ccy property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCcy(String value) {
        this.ccy = value;
    }

    /**
     * Gets the value of the indexfactor property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getIndexfactor() {
        return indexfactor;
    }

    /**
     * Sets the value of the indexfactor property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setIndexfactor(BigDecimal value) {
        this.indexfactor = value;
    }

    /**
     * Gets the value of the red property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRed() {
        return red;
    }

    /**
     * Sets the value of the red property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRed(String value) {
        this.red = value;
    }

    /**
     * Gets the value of the terms property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the terms property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerms().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TermsType }
     *
     *
     */
    public TermsType getTerms() {
        if (terms == null) {
            terms = new TermsType();
        }
        return this.terms;
    }

    /**
     * Gets the value of the component property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the component property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComponentType }
     *
     *
     */
    public List<ComponentType> getComponent() {
        if (component == null) {
            component = new ArrayList<>();
        }
        return this.component;
    }
}
