//
// Ce fichier a été généré par l'implémentation de référence JavaTM Architecture for XML Binding (JAXB), v2.2.6 
// Voir <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Toute modification apportée à ce fichier sera perdue lors de la recompilation du schéma source. 
// Généré le : 2013.01.17 à 01:35:40 PM CET 
//


package org.gaia.fpml.fpml_5.recordkeeping;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A collection of related trades or positions and the corresponding aggregate exposures generated by these.
 * 
 * <p>Classe Java pour Position complex type.
 * 
 * <p>Le fragment de schéma suivant indique le contenu attendu figurant dans cette classe.
 * 
 * <pre>
 * &lt;complexType name="Position">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/recordkeeping}PositionIdAndVersion.model"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/recordkeeping}PositionStatusInfo.model"/>
 *         &lt;element name="reportingRoles" type="{http://www.fpml.org/FpML-5/recordkeeping}ReportingRoles" minOccurs="0"/>
 *         &lt;element name="constituent" type="{http://www.fpml.org/FpML-5/recordkeeping}PositionConstituent" minOccurs="0"/>
 *         &lt;element name="scheduledDate" type="{http://www.fpml.org/FpML-5/recordkeeping}ScheduledDate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="valuation" type="{http://www.fpml.org/FpML-5/recordkeeping}AssetValuation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Position", propOrder = {
    "positionId",
    "version",
    "status",
    "creationDate",
    "originatingEvent",
    "history",
    "reportingRoles",
    "constituent",
    "scheduledDate",
    "valuation"
})
public class Position {

    protected PositionId positionId;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger version;
    protected PositionStatusEnum status;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creationDate;
    protected PositionOriginEnum originatingEvent;
    protected PositionHistory history;
    protected ReportingRoles reportingRoles;
    protected PositionConstituent constituent;
    protected List<ScheduledDate> scheduledDate;
    protected List<AssetValuation> valuation;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Obtient la valeur de la propriété positionId.
     * 
     * @return
     *     possible object is
     *     {@link PositionId }
     *     
     */
    public PositionId getPositionId() {
        return positionId;
    }

    /**
     * Définit la valeur de la propriété positionId.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionId }
     *     
     */
    public void setPositionId(PositionId value) {
        this.positionId = value;
    }

    /**
     * Obtient la valeur de la propriété version.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Définit la valeur de la propriété version.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Obtient la valeur de la propriété status.
     * 
     * @return
     *     possible object is
     *     {@link PositionStatusEnum }
     *     
     */
    public PositionStatusEnum getStatus() {
        return status;
    }

    /**
     * Définit la valeur de la propriété status.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionStatusEnum }
     *     
     */
    public void setStatus(PositionStatusEnum value) {
        this.status = value;
    }

    /**
     * Obtient la valeur de la propriété creationDate.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Définit la valeur de la propriété creationDate.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Obtient la valeur de la propriété originatingEvent.
     * 
     * @return
     *     possible object is
     *     {@link PositionOriginEnum }
     *     
     */
    public PositionOriginEnum getOriginatingEvent() {
        return originatingEvent;
    }

    /**
     * Définit la valeur de la propriété originatingEvent.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionOriginEnum }
     *     
     */
    public void setOriginatingEvent(PositionOriginEnum value) {
        this.originatingEvent = value;
    }

    /**
     * Obtient la valeur de la propriété history.
     * 
     * @return
     *     possible object is
     *     {@link PositionHistory }
     *     
     */
    public PositionHistory getHistory() {
        return history;
    }

    /**
     * Définit la valeur de la propriété history.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionHistory }
     *     
     */
    public void setHistory(PositionHistory value) {
        this.history = value;
    }

    /**
     * Obtient la valeur de la propriété reportingRoles.
     * 
     * @return
     *     possible object is
     *     {@link ReportingRoles }
     *     
     */
    public ReportingRoles getReportingRoles() {
        return reportingRoles;
    }

    /**
     * Définit la valeur de la propriété reportingRoles.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingRoles }
     *     
     */
    public void setReportingRoles(ReportingRoles value) {
        this.reportingRoles = value;
    }

    /**
     * Obtient la valeur de la propriété constituent.
     * 
     * @return
     *     possible object is
     *     {@link PositionConstituent }
     *     
     */
    public PositionConstituent getConstituent() {
        return constituent;
    }

    /**
     * Définit la valeur de la propriété constituent.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionConstituent }
     *     
     */
    public void setConstituent(PositionConstituent value) {
        this.constituent = value;
    }

    /**
     * Gets the value of the scheduledDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduledDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduledDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScheduledDate }
     * 
     * 
     */
    public List<ScheduledDate> getScheduledDate() {
        if (scheduledDate == null) {
            scheduledDate = new ArrayList<ScheduledDate>();
        }
        return this.scheduledDate;
    }

    /**
     * Gets the value of the valuation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssetValuation }
     * 
     * 
     */
    public List<AssetValuation> getValuation() {
        if (valuation == null) {
            valuation = new ArrayList<AssetValuation>();
        }
        return this.valuation;
    }

    /**
     * Obtient la valeur de la propriété id.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Définit la valeur de la propriété id.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
